version: '2.1'
services:
  config:
    image: config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: registry
    restart: always
    depends_on:
          config:
            condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"