version: '2.1'
services:
  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 8082:8082

  post-service:
    build: post-service
    ports:
      - 8085:8085

  notification-service:
    build: notification-service
    ports:
      - 8084:8084